# Generated by Django 4.2.3 on 2023-07-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name_plural': 'User Images'},
        ),
    ]
