# Generated by Django 4.2.3 on 2023-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
