# Generated by Django 4.2.3 on 2023-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='Image',
            field=models.ImageField(default='user_images/No_Image_Available.jpg', upload_to='user_images'),
        ),
    ]
