# Generated by Django 4.2.3 on 2023-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='Image',
            field=models.FileField(default='user_images/No_Image_Available.jpg', upload_to='user_images'),
        ),
    ]
